apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment 
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      env: production
  replicas: 4
  template:
    metadata:
      name: ngix-2
      labels:
        env: production
    spec:
      containers:
        - name: ngix
          image: nginx 
